apiVersion: apps/v1
kind: Deployment
metadata:
  name: next-checkout-deployment
  labels:
    app: next-checkout
spec:
  replicas: 1
  selector:
    matchLabels:
      app: next-checkout
  template:
    metadata:
      labels:
        app: next-checkout
    spec:
      containers:
      - name: next-checkout
        image: mateoecheverrip/checkout:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: checkout
spec:
  type: LoadBalancer
  selector:
    app: next-checkout
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 3000
---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: checkout
# spec:
#   rules:
#   - http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: checkout
#             port:
#               number: 3000