apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-backend-deployment
  labels:
    app: email-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: email-backend
  template:
    metadata:
      labels:
        app: email-backend
    spec:
      containers:
      - name: email-backend
        image: mateoecheverrip/email:V1
        env:
          - name: KAFKA_BROKER
            value: "pkc-12576z.us-west2.gcp.confluent.cloud:9092"
          - name: KAFKA_USERNAME
            value: "MVUKMAXV6YCAXADW"
          - name: KAFKA_SECRET
            value: "HrF+SU5gmsgvlMyDwCJg06Q9Ng+fLM04WAA19SJNV7cXNkJWSwYeHs7f8sGf7V4m"  
        ports:
        - containerPort: 8025
---
apiVersion: v1
kind: Service
metadata:
  name: email
spec:
  selector:
    app: email-backend
  ports:
    - protocol: TCP
      port: 8025
      targetPort: 8025 
