apiVersion: apps/v1
kind: Deployment
metadata:
  name: hardware-shop-deployment
  labels:
    app: hardware-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hardware-shop
  template:
    metadata:
      labels:
        app: hardware-shop
    spec:
      containers:
      - name: hardware-shop
        image: mateoecheverrip/hardware-shop:V4
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: hardware
spec:
  type: LoadBalancer
  selector:
    app: hardware-shop
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
