apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-db
  labels:
    app: mysql-user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-user
  template:
    metadata:
      labels:
        app: mysql-user
    spec:
      containers:
      - name: mysql-user
        image: mysql:8
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: "root"
        ports:
        - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: user-db
spec:
  selector:
    app: mysql-user
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306


